using Macena.GitHub.Models;

namespace Macena.GitHub.Core.Operation
{
    /// <summary>
    /// Base class for implementing operations that validate and process requests asynchronously.
    /// </summary>
    /// <typeparam name="TRequest">The type of request handled by the operation.</typeparam>
    /// <typeparam name="TResponse">The type of response generated by the operation.</typeparam>
    public interface IBaseOperation<TRequest,TResponse>
        where TRequest : OperationRequest
        where TResponse : OperationResponse, new()
    {
        /// <summary>
        /// Validates the request asynchronously.
        /// </summary>
        /// <param name="request">The request to validate.</param>
        /// <returns>A task representing the asynchronous operation, with a result of the validation response.</returns>
        Task<OperationResponse> ValidateAsync(TRequest request);

        /// <summary>
        /// Processes the request asynchronously.
        /// </summary>
        /// <param name="request">The request to process.</param>
        /// <returns>A task representing the asynchronous operation, with a result of the processing response.</returns>
        Task<TResponse> ProcessAsync(TRequest request);
    }
}
